import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { MoonStars } from '@phosphor-icons/react';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { HeaderSelect } from '@/components/ui/header-controls';
import { Grid } from '@/components/layout/grid';
import { HorizontalScrollNav } from '@/components/ui/horizontal-scroll-nav';
import { SunMoonDetailCard } from '../../almanac/SunMoonDetailCard';
import { AlertsPanel } from './shared/AlertsPanel';
import { TideChart } from './shared/TideChart';
import { MarineStatTile } from '../shared/MarineStatTile';
import { MarineCurrentConditionsCard } from '../shared/MarineCurrentConditionsCard';
import { useAlmanac, useAlmanacMoonNames, useAlmanacPositions, useFishingDetail, useMarineDetail, useStation } from '../../../hooks/useWeatherData';
import { useSmartAlmanac } from '../../../hooks/useSmartAlmanac';
import { formatValue } from '../../../utils/format';
import { formatFullDate, formatTime } from '../../../utils/format-date';
import { cardinalFromDegrees } from '../../../utils/wind';
import { addDays } from '../../../utils/station-clock';
import type { AlmanacSnapshot, MarineAlertSummary, MoonNameData, PositionsSnapshot } from '../../../api/types';
import type { components } from '../../../api/generated-types';

export interface FishingTabProps { locationId: string; alerts?: MarineAlertSummary[]; selectedSpecies?: string; onSelectedSpeciesChange?: (species: string) => void; }
const FISHING_ALERT_TYPES = new Set(['marineZone']);
type FishingData = components['schemas']['FishingData'];
type FishingPeriod = components['schemas']['FishingForecast'];
type FishingDay = components['schemas']['FishingDayEntry'];
type FactorName = 'temperature' | 'tideCurrent' | 'pressure';
type FactorRecord = { available?: boolean; source?: string; sourceType?: string; validTime?: string | null; };
type TranslateFn = ReturnType<typeof useTranslation>['t'];
const TIDE_STATES = new Set(['incoming', 'outgoing', 'slack_high', 'slack_low', 'peak_flow']);

function display(value: number | null | undefined, group: Parameters<typeof formatValue>[1], locale: string): string { return value == null ? '—' : formatValue(value, group, locale); }
function timeText(value: string | null | undefined, locale: string, tz: string): string { return value && !Number.isNaN(new Date(value).getTime()) ? formatTime(new Date(value), locale, tz) : '—'; }
function cardinal(value: number | null | undefined, t: (key: string) => string): string { const name = cardinalFromDegrees(value ?? null); return name ? t(`directions.${name}`) : '—'; }
function humanize(value: string): string { return value.replaceAll('_', ' '); }
function dateText(value: string, locale: string, stationTz: string): string { const date = new Date(`${value}T12:00:00Z`); return Number.isNaN(date.getTime()) ? '—' : formatFullDate(date, locale, stationTz); }
function statusClass(status: FishingPeriod['status']): string { return status === 'active' ? 'bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-200' : status === 'less_active' || status === 'low_activity' ? 'bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-200' : status === 'inactive' ? 'bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-200' : 'bg-muted text-muted-foreground'; }
function localizedStatus(t: TranslateFn, status: FishingPeriod['status']): string { return status ? t(`fishing.status.${status}`) : t('fishing.status.unavailable'); }
function localizedTideState(t: TranslateFn, state: string | null | undefined): string { return state && TIDE_STATES.has(state) ? t(`fishing.tideState.${state}`) : t('fishing.tideState.unavailable'); }
function localizedSolunarState(t: TranslateFn, state: string | null | undefined): string { return state ? t(`fishing.solunarState.${state}`) : t('fishing.solunarState.unavailable'); }
function localizeAdjustmentValue(t: TranslateFn, prefix: 'adjustmentFactor' | 'adjustmentState', value: string | null | undefined): string { return value ? t(`fishing.${prefix}.${value}`) : t('fishing.adjustmentUnknown'); }
function periodDetailId(periodStart: string): string { return `fishing-period-detail-${encodeURIComponent(periodStart)}`; }

function factorLabel(name: FactorName, t: (key: string) => string): string { return name === 'temperature' ? t('waterTemp') : name === 'tideCurrent' ? t('fishing.hero.tideState') : t('fishing.pressure'); }
function factorSuitability(period: FishingPeriod, name: FactorName): number | null { return name === 'temperature' ? period.temperatureSuitability : name === 'tideCurrent' ? period.tideCurrentSuitability : period.pressureSuitability; }
function FactorExplanation({ period, locale, stationTz }: { period: FishingPeriod; locale: string; stationTz: string; }) {
  const { t } = useTranslation('marine'); const provenance = period.factorProvenance as Record<string, FactorRecord> | undefined; const factors: FactorName[] = ['temperature', 'tideCurrent', 'pressure'];
  return <section className="mt-4 border-t border-border pt-4" aria-labelledby={`fishing-factors-${period.periodStart}`}><h5 id={`fishing-factors-${period.periodStart}`} className="font-semibold">{t('fishing.conditions')}</h5><dl className="mt-2 grid gap-3 sm:grid-cols-3" style={{ fontSize: 'var(--text-label)' }}>{factors.map((name) => { const record = provenance?.[name]; const suitability = factorSuitability(period, name); const source = record?.available && record.source ? record.source : t('fishing.factorUnavailable'); const sourceType = record?.available && record.sourceType ? t(`fishing.provenanceType.${record.sourceType}`) : null; const validTime = record?.available ? timeText(record.validTime, locale, stationTz) : null; return <div key={name} className="rounded-md bg-muted/50 p-3"><dt className="font-medium">{factorLabel(name, t)}</dt><dd className="mt-1 font-semibold">{suitability == null ? '—' : `${Math.round(suitability * 100)}%`}</dd><dd className="mt-1 text-muted-foreground">{sourceType ? `${sourceType} · ${source}` : source}</dd>{validTime && <dd className="text-muted-foreground">{validTime}</dd>}</div>; })}</dl></section>;
}
function formatAdjustment(t: TFunction, adjustment: unknown): string { if (!adjustment || typeof adjustment !== 'object') return '—'; const item = adjustment as Record<string, unknown>; const factor = typeof item.factor === 'string' ? item.factor : null; const state = typeof item.state === 'string' ? item.state : null; const multiplier = typeof item.multiplier === 'number' && Number.isFinite(item.multiplier) ? item.multiplier : null; const factorText = factor ? localizeAdjustmentValue(t, 'adjustmentFactor', factor) : null; const stateText = state ? localizeAdjustmentValue(t, 'adjustmentState', state) : null; return [factorText, stateText, multiplier == null ? null : `× ${multiplier}`].filter((part): part is string => part !== null).join(' · ') || '—'; }
function PeriodDetail({ period, locale, stationTz, units }: { period: FishingPeriod; locale: string; stationTz: string; units: Record<string, string> | undefined; }) {
  const { t } = useTranslation('marine'); const { t: tCommon } = useTranslation('common');
  return <section id={periodDetailId(period.periodStart)} className="border-t border-border pt-4" aria-live="polite"><h4 className="font-semibold">{t('fishing.periodDetailHeading', { period: period.periodLabel })}</h4><p className="mt-1 text-muted-foreground">{period.conditionsText}</p><dl className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3"><MarineStatTile label={t('fishing.score')} value={period.score == null ? '—' : `${period.score}/100`} /><MarineStatTile label={t('fishing.scoring.title')} value={period.coreScore == null ? '—' : `${period.coreScore}/100`} /><MarineStatTile label={t('fishing.hero.tideState')} value={localizedTideState(t, period.tideState)} /><MarineStatTile label={t('fishing.pressure')} value={display(period.pressureTrend, 'barometer', locale)} unit={period.pressureTrend == null ? undefined : units?.pressure} /><MarineStatTile label={t('fishing.direction')} value={cardinal(period.windDirection, tCommon)} /><MarineStatTile label={t('waterTemp')} value={display(period.waterTemperature, 'temperature', locale)} unit={period.waterTemperature == null ? undefined : units?.temperature} /></dl>{period.hardStopReason && <p className="mt-3 text-destructive">{t(`fishing.hardStop.${period.hardStopReason}`)}</p>}<FactorExplanation period={period} locale={locale} stationTz={stationTz} /><ul className="mt-3 list-disc pl-5 text-muted-foreground" style={{ fontSize: 'var(--text-label)' }}>{period.appliedAdjustments.map((adjustment, index) => <li key={index}>{formatAdjustment(t, adjustment)}</li>)}</ul></section>;
}

const FISHING_COL_W = 132;
const FISHING_ROW_HEADER_W = 112;
const FISHING_CELL_BASE = { flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' } as const;
const FISHING_ROW_HEADER_STYLE = { width: FISHING_ROW_HEADER_W, flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'flex-end', paddingRight: '0.5rem', fontFamily: 'var(--font-sans, Manrope, system-ui, sans-serif)', fontSize: 'var(--text-micro)', fontWeight: 500, color: 'var(--muted-foreground)', whiteSpace: 'nowrap' } as const;
const FISHING_ROW_H = { time: 28, score: 42, tide: 28, waterTemp: 28, pressure: 28, wind: 38, swell: 38, solunar: 28 } as const;
const FISHING_SECTION_DIVIDER = { height: 1, background: 'var(--border)', marginTop: '0.35rem', marginBottom: '0.35rem' } as const;
const FISHING_DETAIL_BG = 'var(--detail-panel-bg, rgba(80,100,255,0.08))';

type FishingDayGroup = { key: string; label: string; periods: FishingPeriod[] };

function FishingScrollForecast({ dayGroups, selectedSpecies, locale, stationTz, units }: { dayGroups: FishingDayGroup[]; selectedSpecies: string; locale: string; stationTz: string; units: Record<string, string> | undefined; }) {
  const { t } = useTranslation('marine'); const { t: tCommon } = useTranslation('common'); const [detailStart, setDetailStart] = useState<string | null>(null);
  const groupsWithIdx = useMemo(() => { let startIdx = 0; return dayGroups.map((group) => { const withIdx = { ...group, startIdx }; startIdx += group.periods.length; return withIdx; }); }, [dayGroups]);
  const detail = useMemo(() => dayGroups.flatMap((group) => group.periods).find((period) => period.periodStart === detailStart) ?? null, [dayGroups, detailStart]);
  const rowHeader = (height: number, label?: string) => <div style={{ ...FISHING_ROW_HEADER_STYLE, height }}>{label && <span>{label}</span>}</div>;
  const cellText = { fontFamily: 'var(--font-sans, Manrope, system-ui, sans-serif)', fontSize: 'var(--text-micro)', color: 'var(--muted-foreground)', lineHeight: 1.2, textAlign: 'center' } as const;
  const renderRow = (rowKey: string, height: number, renderCell: (period: FishingPeriod) => ReactNode) => <div key={rowKey} style={{ display: 'flex', flexDirection: 'row' }}>{groupsWithIdx.flatMap((group) => group.periods.map((period) => <div key={period.periodStart} style={{ width: FISHING_COL_W, height, ...FISHING_CELL_BASE, background: detail?.periodStart === period.periodStart ? FISHING_DETAIL_BG : 'transparent' }}>{renderCell(period)}</div>))}</div>;

  return <div className="flex flex-col gap-3"><HorizontalScrollNav ariaLabel={t('fishing.periodGridScrollAriaLabel')}><div data-testid="fishing-forecast-grid" style={{ display: 'flex', flexDirection: 'row', width: 'max-content', padding: '0 0.25rem 0.5rem' }}>
    <div data-testid="fishing-row-labels" style={{ width: FISHING_ROW_HEADER_W, flexShrink: 0, position: 'sticky', left: 0, zIndex: 2, background: 'rgb(var(--card-glass))', backdropFilter: 'blur(8px)', WebkitBackdropFilter: 'blur(8px)', borderRight: '1px solid var(--border)' }}>
      {rowHeader(22)}{rowHeader(FISHING_ROW_H.time)}{rowHeader(FISHING_ROW_H.score, t('fishing.score'))}<div style={FISHING_SECTION_DIVIDER} />
      {rowHeader(FISHING_ROW_H.tide, t('fishing.hero.tideState'))}{rowHeader(FISHING_ROW_H.waterTemp, t('waterTemp'))}{rowHeader(FISHING_ROW_H.pressure, t('fishing.pressure'))}{rowHeader(FISHING_ROW_H.wind, t('windSpeed'))}{rowHeader(FISHING_ROW_H.swell, t('fishing.swellHeight'))}{rowHeader(FISHING_ROW_H.solunar, t('fishing.solunar'))}
    </div>
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      <div style={{ display: 'flex', flexDirection: 'row', height: 22 }}>{groupsWithIdx.map((group) => <div key={group.key} style={{ width: group.periods.length * FISHING_COL_W, fontFamily: 'var(--font-sans, Manrope, system-ui, sans-serif)', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--muted-foreground)', paddingLeft: '0.25rem', display: 'flex', alignItems: 'center', whiteSpace: 'nowrap' }}>{group.label}</div>)}</div>
      <div style={{ display: 'flex', flexDirection: 'row' }}>{groupsWithIdx.flatMap((group) => group.periods.map((period) => { const selectedPeriod = detail?.periodStart === period.periodStart; const score = period.score == null ? t('fishing.status.unavailable') : `${period.score}/100`; const status = localizedStatus(t, period.status); const start = timeText(period.periodStart, locale, stationTz); const end = timeText(period.periodEnd, locale, stationTz); return <button key={period.periodStart} data-testid="fishing-period-column" type="button" aria-expanded={selectedPeriod} aria-controls={periodDetailId(period.periodStart)} aria-label={t('fishing.periodControlAriaLabel', { period: period.periodLabel, start, end, species: humanize(selectedSpecies), score, status, explanation: period.conditionsText })} onClick={() => setDetailStart((current) => current === period.periodStart ? null : period.periodStart)} className="focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 rounded-sm" style={{ width: FISHING_COL_W, height: FISHING_ROW_H.time, ...FISHING_CELL_BASE, background: selectedPeriod ? FISHING_DETAIL_BG : 'transparent', border: 'none', borderTop: `2px solid ${selectedPeriod ? 'var(--primary)' : 'transparent'}`, cursor: 'pointer' }}><span style={{ fontFamily: 'var(--font-sans, Manrope, system-ui, sans-serif)', fontSize: 'var(--text-label)', fontWeight: 600, color: selectedPeriod ? 'var(--primary)' : 'var(--muted-foreground)', whiteSpace: 'nowrap', lineHeight: 1 }}>{start}</span></button>; }))}</div>
      {renderRow('score', FISHING_ROW_H.score, (period) => <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.2rem' }}><span style={{ fontFamily: 'var(--font-display, Outfit, system-ui, sans-serif)', fontSize: 'var(--text-body)', fontWeight: 700, fontFeatureSettings: '"tnum"', lineHeight: 1, color: period.score == null ? 'var(--muted-foreground)' : 'var(--foreground)' }}>{period.score == null ? '—' : `${period.score}/100`}</span><span className={`rounded-full px-2 py-0.5 font-semibold ${statusClass(period.status)}`} style={{ fontSize: 'var(--text-micro)', lineHeight: 1 }}>{localizedStatus(t, period.status)}</span></div>)}
      <div style={FISHING_SECTION_DIVIDER} />
      {renderRow('tide', FISHING_ROW_H.tide, (period) => <span style={cellText}>{localizedTideState(t, period.tideState)}</span>)}
      {renderRow('water-temp', FISHING_ROW_H.waterTemp, (period) => <span style={cellText}>{period.waterTemperature == null ? '—' : t('fishing.measurement', { value: display(period.waterTemperature, 'temperature', locale), unit: units?.temperature ?? '' })}</span>)}
      {renderRow('pressure', FISHING_ROW_H.pressure, (period) => <span style={cellText}>{period.pressureTrend == null ? '—' : t('fishing.measurement', { value: display(period.pressureTrend, 'barometer', locale), unit: units?.pressure ?? '' })}</span>)}
      {renderRow('wind', FISHING_ROW_H.wind, (period) => <span style={cellText}>{period.windSpeed == null ? '—' : t('fishing.periodWindAriaLabel', { speed: display(period.windSpeed, 'wind', locale), unit: units?.windSpeed ?? '', direction: cardinal(period.windDirection, tCommon) })}</span>)}
      {renderRow('swell', FISHING_ROW_H.swell, (period) => <span style={cellText}>{period.swellHeight == null || period.swellPeriod == null ? '—' : t('fishing.periodSwellAriaLabel', { height: display(period.swellHeight, 'default', locale), heightUnit: units?.waveHeight ?? '', period: display(period.swellPeriod, 'default', locale), periodUnit: units?.wavePeriod ?? '' })}</span>)}
      {renderRow('solunar', FISHING_ROW_H.solunar, (period) => <span style={cellText}>{localizedSolunarState(t, period.solunarState)}</span>)}
    </div>
  </div></HorizontalScrollNav>{detail && <div style={{ background: FISHING_DETAIL_BG, borderRadius: '0.5rem', padding: '0.75rem 1rem 1rem' }}><PeriodDetail period={detail} locale={locale} stationTz={stationTz} units={units} /></div>}</div>;
}

function FishingForecastCard({ data, selectedSpecies, onSelectedSpeciesChange, locale, stationTz, units }: { data: FishingData; selectedSpecies: string; onSelectedSpeciesChange: (species: string) => void; locale: string; stationTz: string; units: Record<string, string> | undefined; }) {
  const { t } = useTranslation('marine'); const dayGroups = useMemo(() => data.days.map((day) => ({ key: day.date, label: dateText(day.date, locale, stationTz), periods: day.periods.filter((period) => period.selectedSpecies === selectedSpecies) })).filter((day) => day.periods.length > 0), [data.days, locale, selectedSpecies, stationTz]);
  return <Card footprint="full"><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle as="h3">{t('fishing.forecastTitle')}</CardTitle><HeaderSelect value={selectedSpecies} options={data.species.map((species) => ({ value: species, label: humanize(species) }))} onChange={onSelectedSpeciesChange} ariaLabel={t('fishing.species')} disabled={!data.species.length} /></div></CardHeader><CardContent className="gap-4 overflow-visible">{dayGroups.length === 0 ? <p className="text-muted-foreground">{t('fishing.noData')}</p> : <FishingScrollForecast dayGroups={dayGroups} selectedSpecies={selectedSpecies} locale={locale} stationTz={stationTz} units={units} />}</CardContent></Card>;
}

function SolunarOverlay({ days, locale, stationTz }: { days: FishingDay[]; locale: string; stationTz: string; }) { const { t } = useTranslation('marine'); return <section aria-labelledby="fishing-solunar-overlay"><h3 id="fishing-solunar-overlay" className="font-semibold">{t('fishing.solunar')}</h3><HorizontalScrollNav ariaLabel={t('fishing.solunarTimelineAriaLabel')}><table className="mt-2 min-w-max w-full border-collapse text-left" style={{ fontSize: 'var(--text-label)' }}><caption className="sr-only">{t('fishing.solunarTimelineAriaLabel')}</caption><thead><tr><th scope="col">{t('fishing.day')}</th><th scope="col"><span className="inline-flex items-center gap-1"><span className="size-2 rounded-sm bg-primary" aria-hidden="true" />{t('fishing.majorPeriod')}</span></th><th scope="col"><span className="inline-flex items-center gap-1"><span className="size-2 rounded-sm bg-muted-foreground" aria-hidden="true" />{t('fishing.minorPeriod')}</span></th></tr></thead><tbody>{days.slice(0, 2).map((day) => <tr key={day.date} className="border-t border-border"><th scope="row">{dateText(day.date, locale, stationTz)}</th><td>{day.solunar.majorPeriods.map((range) => <span key={range.start} className="mr-3 inline-flex items-center gap-1"><MoonStars aria-hidden="true" />{timeText(range.start, locale, stationTz)} – {timeText(range.end, locale, stationTz)}</span>)}</td><td>{day.solunar.minorPeriods.map((range) => <span key={range.start} className="mr-3 inline-block">{timeText(range.start, locale, stationTz)} – {timeText(range.end, locale, stationTz)}</span>)}</td></tr>)}</tbody></table></HorizontalScrollNav></section>; }
function SolunarCard({ days, locale, stationTz, almanac, almanacTomorrow, arcAlmanac, positions, moonNames, loading, error }: { days: FishingDay[]; locale: string; stationTz: string; almanac: AlmanacSnapshot | null; almanacTomorrow: AlmanacSnapshot | null; arcAlmanac: AlmanacSnapshot | null; positions: PositionsSnapshot | null; moonNames: MoonNameData | null; loading: boolean; error: string | null; }) { if (!days.length) return null; return <SunMoonDetailCard almanac={almanac} almanacTomorrow={almanacTomorrow} arcAlmanac={arcAlmanac} positions={positions} moonNames={moonNames} stationTz={stationTz} loading={loading} error={error} overlay={<SolunarOverlay days={days} locale={locale} stationTz={stationTz} />} />; }

export function FishingTab({ locationId, alerts = [], selectedSpecies: selectedSpeciesProp, onSelectedSpeciesChange }: FishingTabProps) {
  const { t, i18n } = useTranslation('marine'); const { t: tCommon } = useTranslation('common'); const [localSelectedSpecies, setLocalSelectedSpecies] = useState(''); const selectedSpecies = selectedSpeciesProp ?? localSelectedSpecies; const setSelectedSpecies = onSelectedSpeciesChange ?? setLocalSelectedSpecies;
  const { data: rawFishing, units, loading, error, refetch } = useFishingDetail(locationId, selectedSpecies || null); const { data: rawMarine } = useMarineDetail(locationId); const { data: station } = useStation(); const fishing = rawFishing as unknown as FishingData | null; const marine = rawMarine as unknown as { observation?: components['schemas']['MarineObservation'] | null } | null; const unitMap = units as Record<string, string> | undefined; const stationTz = station?.timezone ?? 'UTC';
  const fishingCoordinates = fishing?.coordinates?.lat != null && fishing.coordinates.lon != null ? { lat: fishing.coordinates.lat, lon: fishing.coordinates.lon } : undefined; const almanacDate = fishing?.days[0]?.date ?? ''; const almanacTomorrowDate = fishing?.days[1]?.date ?? (almanacDate ? addDays(almanacDate, 1) : ''); const almanac = useAlmanac(almanacDate || undefined, fishingCoordinates); const almanacTomorrow = useAlmanac(almanacTomorrowDate || undefined, fishingCoordinates); const smartAlmanac = useSmartAlmanac(fishingCoordinates, almanacDate || undefined); const positions = useAlmanacPositions(fishingCoordinates); const moonNames = useAlmanacMoonNames(); const species = useMemo(() => fishing?.species ?? [], [fishing]);
  useEffect(() => { if (species.length && !species.includes(selectedSpecies)) setSelectedSpecies(species[0]); }, [selectedSpecies, setSelectedSpecies, species]);
  if (loading) return <div className="flex flex-col gap-[var(--gap-grid)]" aria-busy="true"><span role="status" className="sr-only">{t('fishing.loading')}</span><Grid className="md:!auto-rows-[auto]"><Card footprint="full"><CardHeader><CardTitle as="h3">{t('fishing.forecastTitle')}</CardTitle></CardHeader><CardContent><div className="h-72 animate-pulse rounded-lg bg-muted" aria-hidden="true" /></CardContent></Card></Grid></div>; if (error) return <div role="alert"><p className="text-destructive">{t('fishing.unableToLoad')}</p><button type="button" onClick={refetch} className="focus-visible:ring-2 focus-visible:ring-ring">{tCommon('retry')}</button></div>; if (!fishing) return <p className="text-muted-foreground">{t('fishing.noData')}</p>;
  return <div className="flex flex-col gap-[var(--gap-grid)]"><AlertsPanel alerts={alerts} filterTypes={FISHING_ALERT_TYPES} /><Grid className="md:!auto-rows-[auto]"><MarineCurrentConditionsCard observation={marine?.observation} locale={i18n.language} stationTz={stationTz} units={unitMap} title={t('fishing.currentConditions')} /><FishingForecastCard data={fishing} selectedSpecies={selectedSpecies} onSelectedSpeciesChange={setSelectedSpecies} locale={i18n.language} stationTz={stationTz} units={unitMap} /><SolunarCard days={fishing.days} locale={i18n.language} stationTz={stationTz} almanac={almanac.data} almanacTomorrow={almanacTomorrow.data} arcAlmanac={smartAlmanac.data} positions={positions.data ?? null} moonNames={moonNames.data} loading={almanac.loading} error={almanac.error?.message ?? null} /><Card footprint="full"><CardHeader><CardTitle as="h3">{t('fishing.tides')}</CardTitle></CardHeader><CardContent><TideChart predictions={fishing.tidePredictions.map((prediction) => ({ ...prediction, type: prediction.type ?? null }))} locale={i18n.language} stationTz={stationTz} heightUnit={unitMap?.height ?? 'ft'} ariaLabel={t('fishing.tideChartAriaLabel', { location: fishing.locationName })} /></CardContent></Card></Grid></div>;
}
export default FishingTab;
