// This file is auto-generated from openapi-v1.yaml. Do not edit manually.
// Run `npm run generate:types` to regenerate.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Most recent observation
         * @description Returns the most recent archive record from the weewx database
         *     (the latest record within a small look-back window).
         */
        get: operations["getCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical archive records
         * @description Returns archive records from the weewx database within the
         *     requested time window. Used by the Charts page (composes its
         *     own series from raw history) and the homepage chart panel.
         *
         *     Pagination supports BOTH a forward `cursor` token AND
         *     page-number navigation; clients pick whichever fits per ADR
         *     (paginate sequentially with cursors, or jump to a known page).
         */
        get: operations["getArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Highs and lows
         * @description Section-grouped records (Temperature / Wind / Rain / Humidity /
         *     Barometer / Sun / AQI / InsideTemp + custom). Each section
         *     self-hides when its backing data is unavailable.
         */
        get: operations["getRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast bundle (hourly + daily + discussion)
         * @description From the configured forecast provider per ADR-007. Provider-
         *     specific fields not in the canonical model flow through `extras`.
         */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active severe-weather alerts
         * @description From the configured alerts provider per ADR-016. Returns
         *     `alerts: []` (with `source` set) when the operator has no
         *     configured provider or the provider's coverage doesn't include
         *     the station — no error.
         */
        get: operations["getAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aqi/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current AQI reading
         * @description Source = configured AQI provider OR weewx archive columns per
         *     ADR-013. Same canonical shape either way; `source` indicates
         *     which path was used.
         */
        get: operations["getAqiCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aqi/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical AQI readings
         * @description Reads from clearskies-api's own AQI history store (Path B,
         *     per ADR-013) OR from weewx archive AQI columns (Path A).
         */
        get: operations["getAqiHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/earthquakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent earthquakes within configured radius
         * @description From the configured earthquake provider per ADR-040
         *     (usgs / geonet / emsc / renass). Empty list when nothing in
         *     the time + radius window — not an error.
         */
        get: operations["getEarthquakes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/almanac": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sun and moon snapshot for a given date
         * @description Skyfield-computed locally per ADR-014. Stateless given (lat, lon, date).
         */
        get: operations["getAlmanac"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/almanac/sun-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Year-long sunrise / sunset / daylight series
         * @description Drives the Almanac page's year-long charts.
         */
        get: operations["getSunTimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/almanac/moon-phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Moon-phase calendar
         * @description Returns a month grid (or full year) of moon phases for the
         *     Almanac page calendar.
         */
        get: operations["getMoonPhases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station identity and metadata */
        get: operations["getStation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runtime capability registry
         * @description Per ADR-038, the union of all configured-and-enabled provider
         *     modules' capability declarations, plus the operator's
         *     column-mapping decisions per ADR-035. Drives the dashboard's
         *     sensor-availability self-hide behaviour (ADR-024 cat 10).
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard navigation list
         * @description Built-in pages per ADR-024 plus operator-defined custom pages.
         *     Hidden pages omitted; custom-page slugs come from operator config.
         */
        get: operations["getPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{slug}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page markdown content
         * @description Returns operator-authored markdown content for a named page (ADR-024).
         *     The slug must identify a known page (built-in or custom).  Hidden pages
         *     are still servable — content can be pre-authored before the page is
         *     made visible.
         *
         *     Returns an empty-string markdown with null updatedAt when the page
         *     exists but no content file has been placed in the content directory.
         *     This is not an error; it means the operator has not authored content
         *     for that page yet.
         */
        get: operations["getPageContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chart-group structure
         * @description Built-in groups (`homepage`, `monthly`, `ANNUAL`,
         *     `averageclimate`) plus operator-defined custom groups.
         *     Each group declares its member fields; the dashboard
         *     composes time-series data via `/archive`.
         */
        get: operations["getChartGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available NOAA report files
         * @description Lists the year/month options the dashboard's Reports page can
         *     offer. Derived from the `NOAA-*.txt` files weewx has actually
         *     written to its report directory — both monthly
         *     (`NOAA-YYYY-MM.txt` from `[[SummaryByMonth]]`) and yearly
         *     (`NOAA-YYYY.txt` from `[[SummaryByYear]]`). Each entry's
         *     `kind` distinguishes them. Empty options never appear.
         */
        get: operations["getReportIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One NOAA monthly report (raw text)
         * @description Returns the unmodified contents of the corresponding
         *     `NOAA-{year}-{month}.txt` file weewx generated. The dashboard
         *     parses the fixed-width text into a sortable table client-side.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One NOAA yearly report (raw text)
         * @description Returns the unmodified contents of the corresponding
         *     `NOAA-{year}.txt` file weewx generated via
         *     `[[SummaryByYear]]`. Format is the same fixed-width NOAA
         *     layout as the monthly summary, but spans a full year.
         */
        get: operations["getYearlyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** About-page markdown content */
        get: operations["getAboutContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/legal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legal/privacy page markdown content */
        get: operations["getLegalContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radar/providers/{provider_id}/tiles/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radar map-tile proxy (for keyed providers)
         * @description Server-side proxy per ADR-015 + ADR-037 — keys never reach the
         *     browser. Free keyless providers can be fetched directly by the
         *     browser; this proxy is for keyed paths (`aeris`,
         *     `openweathermap`).
         *
         *     Tile content type and per-provider URL templates are declared
         *     by the radar capability registry; see `/capabilities`.
         */
        get: operations["getRadarTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radar/providers/{provider_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available radar frames (timestamps)
         * @description For time-stepped tile sources. Drives the radar tab's frame-replay control.
         */
        get: operations["getRadarFrames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 when the process is responsive. No external
         *     dependencies checked. Used by orchestrators for "is the process
         *     dead?" decisions.
         */
        get: operations["getHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when the service is ready to serve, including a
         *     `degraded` state where one or more non-critical dependencies are
         *     failing but the service can still handle most requests. Returns
         *     503 only when the service genuinely cannot serve. See ADR-030.
         */
        get: operations["getHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Map of canonical field name → unit string. Per ADR-019: the
         *     unit reflects whatever weewx is configured to write that
         *     field in (its `target_unit`). Server does not convert.
         * @example {
         *       "outTemp": "°F",
         *       "windSpeed": "mph",
         *       "barometer": "inHg",
         *       "rain": "in"
         *     }
         */
        UnitsBlock: {
            [key: string]: string;
        };
        /** @description Pagination metadata. Both cursor and page-number forms supplied. */
        PageInfo: {
            /** @description Opaque token for the next page; null on the last page. */
            cursor?: string;
            /**
             * Format: uri-reference
             * @description Convenience URL of the next page.
             */
            next?: string;
            /** Format: uri-reference */
            previous?: string;
            limit: number;
            /** @description 1-based current page number. */
            page?: number;
            totalPages?: number;
            totalRecords?: number;
        };
        /**
         * @description RFC 9457 Problem Details.
         * @example {
         *       "type": "https://clearskies.weewx.org/errors/validation",
         *       "title": "Invalid query",
         *       "status": 400,
         *       "detail": "limit must be between 1 and 10000",
         *       "instance": "/api/v1/archive"
         *     }
         */
        Problem: {
            /**
             * Format: uri
             * @description URI identifying the problem type.
             */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
        ProviderProblem: components["schemas"]["Problem"] & {
            /** @description Stable provider id (e.g. "aeris", "usgs", "openmeteo"). */
            providerId?: string;
            /** @enum {string} */
            domain?: "forecast" | "alerts" | "aqi" | "earthquakes" | "radar";
            /** @enum {string} */
            errorCode?: "QuotaExhausted" | "KeyInvalid" | "GeographicallyUnsupported" | "FieldUnsupported" | "TransientNetworkError" | "ProviderProtocolError";
            retryAfterSeconds?: number;
        };
        /**
         * @description Most-recent point reading from the weewx archive. The field
         *     set is the FULL weewx-stock canonical observation column set
         *     (wview + wview_extended). Every stock weewx archive column
         *     is a first-class field on this schema; operator-custom
         *     columns route through `extras` per ADR-035.
         *
         *     Operators with archive schemas that omit a field (e.g., a
         *     wview-only install will not have `appTemp`) see `null` for
         *     that field; the JSON key is always present.
         *
         *     Full per-field unit mapping per `target_unit` system lives in
         *     `docs/contracts/canonical-data-model.md`.
         */
        Observation: {
            /** Format: date-time */
            timestamp: string;
            outTemp?: number | null;
            outHumidity?: number | null;
            windSpeed?: number | null;
            windDir?: number | null;
            windGust?: number | null;
            windGustDir?: number | null;
            barometer?: number | null;
            pressure?: number | null;
            altimeter?: number | null;
            dewpoint?: number | null;
            windchill?: number | null;
            heatindex?: number | null;
            rainRate?: number | null;
            rain?: number | null;
            radiation?: number | null;
            UV?: number | null;
            inTemp?: number | null;
            inHumidity?: number | null;
            ET?: number | null;
            hail?: number | null;
            hailRate?: number | null;
            appTemp?: number | null;
            cloudbase?: number | null;
            cloudcover?: number | null;
            windrun?: number | null;
            maxSolarRad?: number | null;
            sunshineDur?: number | null;
            daySunshineDur?: number | null;
            rainDur?: number | null;
            THSW?: number | null;
            humidex?: number | null;
            pop?: number | null;
            illuminance?: number | null;
            noise?: number | null;
            lightning_strike_count?: number | null;
            lightning_distance?: number | null;
            lightning_noise_count?: number | null;
            lightning_disturber_count?: number | null;
            snow?: number | null;
            snowDepth?: number | null;
            snowRate?: number | null;
            vecdir?: number | null;
            gustdir?: number | null;
            vecavg?: number | null;
            rms?: number | null;
            heatdeg?: number | null;
            cooldeg?: number | null;
            extraTemp1?: number | null;
            extraTemp2?: number | null;
            extraTemp3?: number | null;
            extraHumid1?: number | null;
            extraHumid2?: number | null;
            soilTemp1?: number | null;
            soilTemp2?: number | null;
            soilTemp3?: number | null;
            soilTemp4?: number | null;
            soilMoist1?: number | null;
            soilMoist2?: number | null;
            soilMoist3?: number | null;
            soilMoist4?: number | null;
            leafTemp1?: number | null;
            leafTemp2?: number | null;
            leafWet1?: number | null;
            leafWet2?: number | null;
            consBatteryVoltage?: number | null;
            heatingVoltage?: number | null;
            referenceVoltage?: number | null;
            supplyVoltage?: number | null;
            rxCheckPercent?: number | null;
            /**
             * @description Operator-custom weewx columns keyed by the weewx column
             *     name verbatim. Stock weewx columns NEVER appear here —
             *     they are first-class fields above. `extras` is the
             *     operator-extension surface (ADR-035 mapping flow). May
             *     be empty.
             */
            extras?: {
                [key: string]: number | string | boolean | null;
            };
            /** @description Always `"weewx"` for archive-derived records. */
            source: string;
        };
        ArchiveRecord: components["schemas"]["Observation"] & {
            /** @description Archive interval length in minutes (typical 5). */
            interval: number;
        };
        HourlyForecastPoint: {
            /** Format: date-time */
            validTime: string;
            outTemp?: number | null;
            outHumidity?: number | null;
            windSpeed?: number | null;
            windDir?: number | null;
            windGust?: number | null;
            precipProbability?: number | null;
            precipAmount?: number | null;
            precipType?: string | null;
            cloudCover?: number | null;
            weatherCode?: string | null;
            weatherText?: string | null;
            source: string;
            extras?: components["schemas"]["Observation"]["extras"];
        };
        DailyForecastPoint: {
            /** Format: date */
            validDate: string;
            tempMax?: number | null;
            tempMin?: number | null;
            precipAmount?: number | null;
            precipProbabilityMax?: number | null;
            windSpeedMax?: number | null;
            windGustMax?: number | null;
            /** Format: date-time */
            sunrise?: string | null;
            /** Format: date-time */
            sunset?: string | null;
            uvIndexMax?: number | null;
            weatherCode?: string | null;
            weatherText?: string | null;
            /** @description Multi-sentence per-day summary (NWS, some Aeris plans). */
            narrative?: string | null;
            source: string;
            extras?: components["schemas"]["Observation"]["extras"];
        };
        /** @description Free-form prose forecast (NWS AFD or equivalent). */
        ForecastDiscussion: {
            headline?: string;
            /** @description Plain text or basic Markdown. */
            body: string;
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            validFrom?: string | null;
            /** Format: date-time */
            validUntil?: string | null;
            senderName?: string | null;
            source: string;
        };
        ForecastBundle: {
            hourly: components["schemas"]["HourlyForecastPoint"][];
            daily: components["schemas"]["DailyForecastPoint"][];
            discussion?: components["schemas"]["ForecastDiscussion"] | null;
            source: string;
            /** Format: date-time */
            generatedAt: string;
        };
        AlertRecord: {
            id: string;
            headline: string;
            description?: string;
            /** @enum {string} */
            severity: "advisory" | "watch" | "warning";
            urgency?: string | null;
            certainty?: string | null;
            event: string;
            /** Format: date-time */
            effective: string;
            /** Format: date-time */
            expires?: string | null;
            senderName?: string | null;
            areaDesc?: string | null;
            category?: string | null;
            source: string;
        };
        AlertList: {
            alerts: components["schemas"]["AlertRecord"][];
            /** Format: date-time */
            retrievedAt: string;
            source: string;
        };
        /**
         * @description Per ADR-010 / ADR-040. Required fields are what every
         *     provider supplies; optional fields are what some providers
         *     supply (USGS PAGER alert, GeoNet MMI, etc.).
         */
        EarthquakeRecord: {
            /** @description Provider's stable event ID. */
            id: string;
            /** Format: date-time */
            time: string;
            latitude: number;
            longitude: number;
            magnitude: number;
            /** @description e.g. mw, ml, md, mb. */
            magnitudeType?: string | null;
            /** @description Kilometers below surface. */
            depth?: number | null;
            /** @description Human-readable location ("12 km NE of Wellington"). */
            place?: string | null;
            /** Format: uri */
            url?: string | null;
            tsunami?: boolean | null;
            /** @description Count of "did you feel it" reports (USGS). */
            felt?: number | null;
            /** @description Modified Mercalli Intensity (USGS estimate or GeoNet measured). */
            mmi?: number | null;
            /**
             * @description USGS PAGER alert level.
             * @enum {string|null}
             */
            alert?: "green" | "yellow" | "orange" | "red" | null;
            /** @description Review status (provider-dependent vocabulary). */
            status?: string | null;
            extras?: components["schemas"]["Observation"]["extras"];
            source: string;
        };
        AQIReading: {
            aqi?: number | null;
            /**
             * @description EPA category name (Good / Moderate / Unhealthy for
             *     Sensitive Groups / Unhealthy / Very Unhealthy / Hazardous).
             */
            aqiCategory?: string | null;
            /** @description Canonical pollutant identifier (e.g. "PM2.5", "O3"). */
            aqiMainPollutant?: string | null;
            aqiLocation?: string | null;
            pollutantPM25?: number | null;
            pollutantPM10?: number | null;
            pollutantO3?: number | null;
            pollutantNO2?: number | null;
            pollutantSO2?: number | null;
            pollutantCO?: number | null;
            /** Format: date-time */
            observedAt: string;
            /**
             * @description `"weewx"` when read from archive columns (Path A);
             *     provider id when from a clearskies-api AQI module (Path B).
             */
            source: string;
        };
        StationMetadata: {
            /**
             * @description Stable identifier for the station. v0.1 single-station
             *     (per ADR-011) — typically derived from operator config.
             */
            stationId: string;
            name: string;
            latitude: number;
            longitude: number;
            /** @description Above mean sea level. Value is in the unit named by `units.altitude` per ADR-019; server emits whatever unit weewx is configured to write (no server-side conversion). */
            altitude: number;
            /**
             * @description IANA TZ identifier (e.g. "America/New_York"). Source
             *     priority per ADR-020.
             */
            timezone: string;
            /** @description Current offset from UTC in minutes. */
            timezoneOffsetMinutes?: number;
            /**
             * @description Active weewx target_unit per ADR-019.
             * @enum {string}
             */
            unitSystem: "US" | "METRIC" | "METRICWX";
            /** Format: date-time */
            firstRecord?: string | null;
            /** Format: date-time */
            lastRecord?: string | null;
            hardware?: string | null;
            /**
             * @description Default locale for the dashboard (ADR-021). One of the 13 supported
             *     locale codes. The dashboard uses this as the initial language, with
             *     browser preference as a fallback.
             * @example en
             */
            defaultLocale?: string;
        };
        /** @description Sun + moon snapshot for a given date. Skyfield-computed. */
        AlmanacSnapshot: {
            /** Format: date */
            date: string;
            sun: {
                /** Format: date-time */
                rise?: string | null;
                /** Format: date-time */
                set?: string | null;
                /** Format: date-time */
                transit?: string | null;
                /** Format: date-time */
                civilTwilightDawn?: string | null;
                /** Format: date-time */
                civilTwilightDusk?: string | null;
                azimuth?: number | null;
                altitude?: number | null;
                rightAscension?: number | null;
                declination?: number | null;
                daylightMinutes?: number | null;
                daylightDeltaVsYesterdayMinutes?: number | null;
                /** Format: date-time */
                nextEquinox?: string | null;
                /** Format: date-time */
                nextSolstice?: string | null;
            };
            moon: {
                /** Format: date-time */
                rise?: string | null;
                /** Format: date-time */
                set?: string | null;
                /** Format: date-time */
                transit?: string | null;
                azimuth?: number | null;
                altitude?: number | null;
                rightAscension?: number | null;
                declination?: number | null;
                /** @enum {string|null} */
                phaseName?: "new" | "waxing-crescent" | "first-quarter" | "waxing-gibbous" | "full" | "waning-gibbous" | "last-quarter" | "waning-crescent" | null;
                illuminationPercent?: number | null;
                /** Format: date-time */
                nextFullMoon?: string | null;
                /** Format: date-time */
                nextNewMoon?: string | null;
            };
        };
        SunTimesSeries: {
            year: number;
            days: {
                /** Format: date */
                date: string;
                /** Format: date-time */
                sunrise?: string | null;
                /** Format: date-time */
                sunset?: string | null;
                daylightMinutes?: number | null;
            }[];
        };
        MoonPhaseCalendar: {
            year: number;
            /** @description Null when the response is the full year. */
            month?: number | null;
            days: {
                /** Format: date */
                date: string;
                phaseName: components["schemas"]["AlmanacSnapshot"]["moon"]["phaseName"];
                illuminationPercent: number;
            }[];
        };
        /** @description One named record (e.g. "All-time high outTemp"). */
        RecordEntry: {
            label: string;
            /** @description Canonical field name this record measures. */
            canonicalField: string;
            value?: number | null;
            /** Format: date-time */
            observedAt?: string | null;
            /** @default false */
            brokenInLast30Days: boolean;
        };
        /** @description Records grouped by section per ADR-024. */
        RecordsBundle: {
            /** @description ytd | all-time | YYYY */
            period: string;
            /** @description Section name → list of record entries. */
            sections: {
                [key: string]: components["schemas"]["RecordEntry"][];
            };
        };
        /**
         * @description One NOAA report file weewx has generated. weewx writes both
         *     monthly summaries (`NOAA-YYYY-MM.txt` via `[[SummaryByMonth]]`)
         *     and yearly summaries (`NOAA-YYYY.txt` via `[[SummaryByYear]]`).
         *     `kind` distinguishes the two; `month` is absent for `yearly`.
         */
        ReportEntry: {
            /** @enum {string} */
            kind: "monthly" | "yearly";
            year: number;
            /** @description 1..12 for `monthly`; absent / null for `yearly`. */
            month?: number | null;
            filename: string;
            /** Format: date-time */
            modifiedAt: string;
        };
        ReportIndex: {
            reports: components["schemas"]["ReportEntry"][];
        };
        /**
         * @description Raw text contents of one weewx-generated `NOAA-YYYY-MM.txt`
         *     monthly summary. Dashboard parses the fixed-width text for
         *     table view; preserves raw text for the "Download .txt" link.
         */
        NOAAReport: {
            year: number;
            month: number;
            filename: string;
            rawText: string;
            /** Format: date-time */
            modifiedAt?: string;
        };
        /**
         * @description Raw text contents of one weewx-generated `NOAA-YYYY.txt`
         *     yearly summary. Same generator as `NOAAReport` but spans the
         *     whole year and has no `month` field.
         */
        NOAAYearlyReport: {
            year: number;
            filename: string;
            rawText: string;
            /** Format: date-time */
            modifiedAt: string;
        };
        PageMetadata: {
            /** @description URL slug, e.g. 'now', 'forecast'. */
            slug: string;
            name: string;
            /** @description Lucide icon name. */
            icon: string;
            navPosition: number;
            builtIn: boolean;
            /** @default false */
            hidden: boolean;
        };
        PageList: {
            pages: components["schemas"]["PageMetadata"][];
        };
        ChartGroup: {
            /** @description e.g. 'homepage', 'monthly', 'ANNUAL', or operator-custom slug. */
            id: string;
            name: string;
            builtIn: boolean;
            /** @description Canonical field names plotted in this group. */
            members: string[];
            /** @description e.g. "1d", "30d", or null when group has its own selector model. */
            defaultRange?: string | null;
        };
        ChartGroupList: {
            groups: components["schemas"]["ChartGroup"][];
        };
        /** @description Per ADR-038 rule 4. One per configured-and-enabled provider module. */
        CapabilityDeclaration: {
            providerId: string;
            /** @enum {string} */
            domain: "forecast" | "alerts" | "aqi" | "earthquakes" | "radar";
            suppliedCanonicalFields: string[];
            /** @description "global" or operator-meaningful region descriptor. */
            geographicCoverage: string;
            defaultPollIntervalSeconds?: number;
            operatorNotes?: string | null;
            /** @description XYZ slippy tile URL template ({z}/{x}/{y} placeholders). Radar XYZ providers only. */
            tileUrlTemplate?: string | null;
            /** @description WMS GetMap base URL. Radar WMS-T providers only. */
            wmsEndpointUrl?: string | null;
            /** @description WMS layer name. Radar WMS-T providers only. */
            wmsLayerName?: string | null;
            /** @description MIME type for tile content (e.g. image/png). All radar providers. */
            tileContentType?: string | null;
            /** @description Operator-supplied iframe URL. iframe radar provider only. */
            iframeUrl?: string | null;
        };
        CapabilityRegistry: {
            providers: components["schemas"]["CapabilityDeclaration"][];
            /**
             * @description Canonical fields supplied by the weewx archive (auto-mapped
             *     stock columns + operator-mapped custom columns per ADR-035).
             */
            weewxColumns: {
                canonicalField: string;
                archiveColumn: string;
            }[];
            /** @description Union of fields supplied by any configured source. */
            canonicalFieldsAvailable: string[];
        };
        MarkdownContent: {
            markdown: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        RadarFrame: {
            /** Format: date-time */
            time: string;
            /** @enum {string} */
            kind: "past" | "current" | "nowcast";
            /**
             * @description Per-frame tile path (set by RainViewer; null for WMS-T providers).
             *     Dashboard combines this with the response-level `tileHost` plus
             *     the provider's CAPABILITY.tile_url_template (`{host}{path}/...`)
             *     to construct the per-frame tile URL. WMS-T providers compose
             *     tile URLs via the `?TIME=<frame.time>` query parameter on
             *     CAPABILITY.wms_endpoint_url instead and leave this null.
             *     Added 3b-14 auditor F2.
             */
            path?: string | null;
        };
        RadarFrameList: {
            providerId: string;
            frames: components["schemas"]["RadarFrame"][];
            attribution?: string | null;
            /**
             * @description Per-fetch tile-server host (set by RainViewer from its JSON
             *     envelope's `host` field; null for WMS-T providers, which carry
             *     their endpoint URL on CAPABILITY.wms_endpoint_url instead).
             *     The dashboard substitutes this into CAPABILITY.tile_url_template's
             *     `{host}` placeholder. Added 3b-14 auditor F2.
             */
            tileHost?: string | null;
        };
        HealthCheck: {
            /** @enum {string} */
            status: "ok" | "warning" | "error";
            messages?: string[];
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unhealthy";
            checks: {
                [key: string]: components["schemas"]["HealthCheck"];
            };
        };
        ObservationResponse: {
            data: components["schemas"]["Observation"] | null;
            units: components["schemas"]["UnitsBlock"];
            source: string;
            /** Format: date-time */
            generatedAt: string;
        };
        ArchiveResponse: {
            data: components["schemas"]["ArchiveRecord"][];
            units: components["schemas"]["UnitsBlock"];
            source: string;
            /** Format: date-time */
            generatedAt: string;
            page: components["schemas"]["PageInfo"];
        };
        RecordsResponse: {
            data: components["schemas"]["RecordsBundle"];
            units: components["schemas"]["UnitsBlock"];
            source: string;
            /** Format: date-time */
            generatedAt: string;
        };
        ForecastResponse: {
            data: components["schemas"]["ForecastBundle"];
            units: components["schemas"]["UnitsBlock"];
            source: string;
            /** Format: date-time */
            generatedAt: string;
        };
        AlertListResponse: {
            data: components["schemas"]["AlertList"];
            source: string;
            /** Format: date-time */
            generatedAt: string;
        };
        AQIResponse: {
            data: components["schemas"]["AQIReading"] | null;
            units: components["schemas"]["UnitsBlock"];
            source: string;
            /** Format: date-time */
            generatedAt: string;
        };
        AQIHistoryResponse: {
            data: components["schemas"]["AQIReading"][];
            units: components["schemas"]["UnitsBlock"];
            source: string;
            /** Format: date-time */
            generatedAt: string;
            page: components["schemas"]["PageInfo"];
        };
        EarthquakeListResponse: {
            data: components["schemas"]["EarthquakeRecord"][];
            source: string;
            /** Format: date-time */
            generatedAt: string;
        };
        AlmanacResponse: {
            data: components["schemas"]["AlmanacSnapshot"];
            /** Format: date-time */
            generatedAt: string;
        };
        SunTimesResponse: {
            data: components["schemas"]["SunTimesSeries"];
            /** Format: date-time */
            generatedAt: string;
        };
        MoonPhaseResponse: {
            data: components["schemas"]["MoonPhaseCalendar"];
            /** Format: date-time */
            generatedAt: string;
        };
        StationResponse: {
            data: components["schemas"]["StationMetadata"];
            units: components["schemas"]["UnitsBlock"];
            /** Format: date-time */
            generatedAt: string;
        };
        CapabilityResponse: {
            data: components["schemas"]["CapabilityRegistry"];
            /** Format: date-time */
            generatedAt: string;
        };
        PageListResponse: {
            data: components["schemas"]["PageList"];
            /** Format: date-time */
            generatedAt: string;
        };
        ChartGroupResponse: {
            data: components["schemas"]["ChartGroupList"];
            /** Format: date-time */
            generatedAt: string;
        };
        ReportIndexResponse: {
            data: components["schemas"]["ReportIndex"];
            /** Format: date-time */
            generatedAt: string;
        };
        ReportResponse: {
            data: components["schemas"]["NOAAReport"];
            /** Format: date-time */
            generatedAt: string;
        };
        YearlyReportResponse: {
            data: components["schemas"]["NOAAYearlyReport"];
            /** Format: date-time */
            generatedAt: string;
        };
        MarkdownResponse: {
            data: components["schemas"]["MarkdownContent"];
            /** Format: date-time */
            generatedAt: string;
        };
        RadarFramesResponse: {
            data: components["schemas"]["RadarFrameList"];
            /** Format: date-time */
            generatedAt: string;
        };
    };
    responses: {
        /** @description Generic error (RFC 9457 problem+json) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Upstream provider failure. `errorCode` carries the ADR-038
         *     taxonomy string (`KeyInvalid`, `TransientNetworkError`,
         *     `ProviderProtocolError`).
         */
        ProviderError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProviderProblem"];
            };
        };
        /**
         * @description Provider quota exhausted or temporarily unavailable. May carry
         *     `Retry-After`.
         */
        ProviderUnavailable: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProviderProblem"];
            };
        };
    };
    parameters: {
        /** @description Lower bound (UTC ISO 8601 with `Z`). Inclusive. */
        From: string;
        /** @description Upper bound (UTC ISO 8601 with `Z`). Exclusive. */
        To: string;
        /**
         * @description Aggregation level. `raw` returns archive-interval rows
         *     unchanged; `hour` and `day` return the corresponding weewx
         *     aggregations.
         */
        Interval: "raw" | "hour" | "day";
        /**
         * @description Comma-separated list of canonical field names (e.g.
         *     `outTemp,outHumidity,windSpeed`). Omit to return all available.
         */
        Fields: string;
        /** @description Maximum records per page. */
        Limit: number;
        /**
         * @description Opaque pagination token from a prior response's `page.cursor`.
         *     Mutually exclusive with `page`.
         */
        Cursor: string;
        /**
         * @description 1-based page number. Mutually exclusive with `cursor`.
         *     Useful for direct navigation; cursor is preferred for
         *     sequential iteration of large archives.
         */
        Page: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current observation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationResponse"];
                };
            };
            503: components["responses"]["ProviderUnavailable"];
            default: components["responses"]["Problem"];
        };
    };
    getArchive: {
        parameters: {
            query?: {
                /** @description Lower bound (UTC ISO 8601 with `Z`). Inclusive. */
                from?: components["parameters"]["From"];
                /** @description Upper bound (UTC ISO 8601 with `Z`). Exclusive. */
                to?: components["parameters"]["To"];
                /**
                 * @description Aggregation level. `raw` returns archive-interval rows
                 *     unchanged; `hour` and `day` return the corresponding weewx
                 *     aggregations.
                 */
                interval?: components["parameters"]["Interval"];
                /**
                 * @description Comma-separated list of canonical field names (e.g.
                 *     `outTemp,outHumidity,windSpeed`). Omit to return all available.
                 */
                fields?: components["parameters"]["Fields"];
                /** @description Maximum records per page. */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description Opaque pagination token from a prior response's `page.cursor`.
                 *     Mutually exclusive with `page`.
                 */
                cursor?: components["parameters"]["Cursor"];
                /**
                 * @description 1-based page number. Mutually exclusive with `cursor`.
                 *     Useful for direct navigation; cursor is preferred for
                 *     sequential iteration of large archives.
                 */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRecords: {
        parameters: {
            query?: {
                period?: string;
                /** @description Restrict to a single section. Omit for all. */
                section?: "temperature" | "wind" | "rain" | "humidity" | "barometer" | "sun" | "aqi";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Records bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordsResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getForecast: {
        parameters: {
            query?: {
                /** @description Number of hourly points (provider-capped). */
                hours?: number;
                /** @description Number of daily points (provider-capped). */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forecast bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            502: components["responses"]["ProviderError"];
            503: components["responses"]["ProviderUnavailable"];
            default: components["responses"]["Problem"];
        };
    };
    getAlerts: {
        parameters: {
            query?: {
                /** @description Filter by minimum severity level. */
                severity?: "advisory" | "watch" | "warning";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            502: components["responses"]["ProviderError"];
            503: components["responses"]["ProviderUnavailable"];
            default: components["responses"]["Problem"];
        };
    };
    getAqiCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current AQI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AQIResponse"];
                };
            };
            502: components["responses"]["ProviderError"];
            503: components["responses"]["ProviderUnavailable"];
            default: components["responses"]["Problem"];
        };
    };
    getAqiHistory: {
        parameters: {
            query?: {
                /** @description Lower bound (UTC ISO 8601 with `Z`). Inclusive. */
                from?: components["parameters"]["From"];
                /** @description Upper bound (UTC ISO 8601 with `Z`). Exclusive. */
                to?: components["parameters"]["To"];
                /** @description Maximum records per page. */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description Opaque pagination token from a prior response's `page.cursor`.
                 *     Mutually exclusive with `page`.
                 */
                cursor?: components["parameters"]["Cursor"];
                /**
                 * @description 1-based page number. Mutually exclusive with `cursor`.
                 *     Useful for direct navigation; cursor is preferred for
                 *     sequential iteration of large archives.
                 */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical AQI page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AQIHistoryResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getEarthquakes: {
        parameters: {
            query?: {
                /** @description Lower bound (UTC ISO 8601 with `Z`). Inclusive. */
                from?: components["parameters"]["From"];
                /** @description Upper bound (UTC ISO 8601 with `Z`). Exclusive. */
                to?: components["parameters"]["To"];
                /** @description Filter to events at or above this magnitude. */
                min_magnitude?: number;
                /**
                 * @description Override the operator-configured radius (kilometers from
                 *     station lat/lon). Omit to use config default.
                 */
                radius_km?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent earthquakes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarthquakeListResponse"];
                };
            };
            502: components["responses"]["ProviderError"];
            503: components["responses"]["ProviderUnavailable"];
            default: components["responses"]["Problem"];
        };
    };
    getAlmanac: {
        parameters: {
            query?: {
                /** @description ISO date (YYYY-MM-DD). Default = station-local today. */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Almanac snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlmanacResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSunTimes: {
        parameters: {
            query?: {
                /** @description Four-digit year. Default = current year. */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sun-times series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SunTimesResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMoonPhases: {
        parameters: {
            query?: {
                year?: number;
                /** @description 1-12. Omit for the full year. */
                month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moon-phase calendar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoonPhaseResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getStation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Station metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPageContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Page slug (e.g. "now", "about", "legal"). */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page markdown content (may be empty string if not yet authored) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkdownResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getChartGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartGroupResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReportIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report index */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportIndexResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw report text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Report file does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getYearlyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw report text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearlyReportResponse"];
                };
            };
            /** @description Report file does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAboutContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description About content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkdownResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getLegalContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Legal content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkdownResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRadarTile: {
        parameters: {
            query?: {
                /**
                 * @description Frame timestamp for time-stepped sources. ISO 8601 UTC.
                 *     Omit for the source's "current" frame.
                 */
                t?: string;
            };
            header?: never;
            path: {
                provider_id: string;
                /** @description Slippy-map zoom level. */
                z: number;
                /** @description Slippy-map tile X. */
                x: number;
                /** @description Slippy-map tile Y. */
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tile image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/webp": string;
                    "image/jpeg": string;
                };
            };
            /** @description Tile not produced (zoom out of range, etc.) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            502: components["responses"]["ProviderError"];
            503: components["responses"]["ProviderUnavailable"];
            default: components["responses"]["Problem"];
        };
    };
    getRadarFrames: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frame list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarFramesResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready (or degraded but serving) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
